public Class A000
//HelloAR
// test pmt
// test alondra

// alon alon
// comment by pmt
{
public Account createAccount(String name)  //method to create account
{
Account sai231111= new Account();
sai231111.Name = name;
return sai231111;
//dsdsd1234111
//NewPR1ssvxcvcvcvcv11
//upodarevcxvxcbcbcbcnvvbnvbnbmbmb
//cg
//new11111111jhgj
//review art change
//Int Chnage
//authenticationhook test sai1234455 nffffff Tewstbewewqewrf
//dfsdfdsfalm test f
}
}